### ISSUE TITLE
interfaces container writer fails.  seems to rely on broker?

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#400]
Following the readme on robokop-interfaces, the interfaces container isn't able to start writer.  Shelling into the container and trying to start it by hand produces this error:
```
Traceback (most recent call last):
  File "robokop-interfaces/builder/writer.py", line 28, in <module>
    credentials=pika.credentials.PlainCredentials(os.environ['BROKER_USER'], os.environ['BROKER_PASSWORD'])
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 564, in _resolve
    self._flags)
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
Failed to write data to connection Address(host='172.18.0.2', port=7687) ("0; 'Underlying socket connection gone (_ssl.c:2061)'")
Failed to write data to connection Address(host='172.18.0.2', port=7687) ("0; 'Underlying socket connection gone (_ssl.c:2061)'")
```

**Comment by cbizon** [comment]
It looks like it's complaining that it can't get to broker?  But Broker isn't part of robokop-interfaces.

**Comment by kennethmorton** [comment]
Writer does require a rabbit MQ broker. As does other stuff in manager. We had to pick a place to put the broker container and we picked manager (the main robokop repo). Is there a desire to be able to only use robokop-interfaces without also cloning robokop? 

Either way here are some options:

1. Another repo for robokop-helpers There are some other containers that might make sense there.
2. Copy the docker-compose.yml for the broker into robokop-interfaces as well as robokop
3. Keep it in robokop

None of these seem great.

**Comment by patrickkwang** [comment]
We could replace RabbitMQ for interfaces with a little Redis queue. We already have a Redis instance there for the builder cache, so it wouldn't mean new ports/containers. We'd just have to make sure they can share nicely.

**Comment by cbizon** [comment]
Yeah, the hope was to be able to stand up robokop-interfaces independently.  That's really driven mostly by the publication strategy, but also a bit by obesity hub, which so far isn't using the manager (except that it needs broker).

The RabbitMQ for writer seems to work well, I don't know if there would be any pain in moving to redis for that?  Still, I agree @kennethmorton that none of the other options are super.  I guess a robokop-helpers repo is the best option of those 3. 

I don't know that this is terribly high priority, though we are going to submit the kg app note soon, so if nothing else, we need to update the robokop-interfaces docs.
