### ISSUE TITLE
Error while importing robokopkg dump

### ISSUE THREAD

**Issue by Prakash2403** [NCATS-Gamma/robokop#490]
Tried to import the latest dump: `graph.9.9.19.dump.db.`

Got this error. Please help.
```
robokop-interfaces/scripts/setup_neo4j_index.py:3: DeprecationWarning: The 'neo4j.v1' package is depr"""Get Neo4j index setup cypher."""
ecated, import from 'neo4j' instead
  from neo4j.v1 import GraphDatabase, basic_auth
Traceback (most recent call last):
  File "robokop-interfaces/scripts/setup_neo4j_index.py", line 11, in <module>
    predicates = list(row['predicate'] for row in result)
  File "robokop-interfaces/scripts/setup_neo4j_index.py", line 11, in <genexpr>
    predicates = list(row['predicate'] for row in result)
  File "/opt/conda/lib/python3.7/site-packages/neo4j/__init__.py", line 952, in records
    self._session.fetch()
  File "/opt/conda/lib/python3.7/site-packages/neo4j/__init__.py", line 527, in fetch
    detail_count, _ = self._connection.fetch()
  File "/opt/conda/lib/python3.7/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/opt/conda/lib/python3.7/site-packages/neobolt/direct.py", line 464, in _fetch
    response.on_failure(summary_metadata or {})
  File "/opt/conda/lib/python3.7/site-packages/neobolt/direct.py", line 759, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.DatabaseError: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]]

```

**Comment by Prakash2403** [comment]
@YaphetKG @patrickkwang Any updates on this?

**Comment by YaphetKG** [comment]
Hi @Prakash2403  sorry for late reply, can you share the neo4j debug logs

**Comment by Prakash2403** [comment]
Hi @YaphetKG , here are the logs related to uploading `graph.9.9.19.dump.db.`

Thanks for the help. Also, any updates on #491 ?
```
2019-12-06 11:52:45.897+0000 INFO [o.n.b.BoltServer] Bolt server loaded
2019-12-06 11:52:46.048+0000 INFO [o.n.b.BoltServer] Bolt enabled on 0.0.0.0:7687.
2019-12-06 11:52:47.363+0000 INFO [o.n.i.d.DiagnosticsManager] --- SERVER STARTED START ---
2019-12-06 11:52:48.177+0000 INFO [o.n.i.d.DiagnosticsManager] --- SERVER STARTED END ---
2019-12-06 11:56:28.151+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]], reference bb77032a-041c-4456-aba8-6a37c53f0c84.
2019-12-06 11:56:28.151+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]], reference bb77032a-041c-4456-aba8-6a37c53f0c84. NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]]
java.lang.IllegalStateException: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]]
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordRelationshipTraversalCursor.computeNext(RecordRelationshipTraversalCursor.java:262)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordRelationshipTraversalCursor.next(RecordRelationshipTraversalCursor.java:157)
	at org.neo4j.kernel.impl.newapi.DefaultRelationshipTraversalCursor.next(DefaultRelationshipTraversalCursor.java:275)
	at org.neo4j.internal.kernel.api.helpers.RelationshipSparseSelection.fetchNext(RelationshipSparseSelection.java:134)
	at org.neo4j.internal.kernel.api.helpers.RelationshipSparseSelectionCursor.next(RelationshipSparseSelectionCursor.java:30)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anon$5.fetchNext(TransactionBoundQueryContext.scala:211)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anon$5.fetchNext(TransactionBoundQueryContext.scala:207)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$CursorIterator.next(TransactionBoundQueryContext.scala:1100)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:445)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.runtime.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:53)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:76)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.accept(StandardInternalExecutionResult.scala:192)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$safelyAndClose$1.apply(ClosingExecutionResult.scala:171)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.safelyAndClose(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:157)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:73)
	at org.neo4j.bolt.v1.messaging.ResultHandler.onRecords(ResultHandler.java:40)
	at org.neo4j.bolt.v3.runtime.StreamingState.lambda$processStreamResultMessage$0(StreamingState.java:41)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:484)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:328)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:128)
	at org.neo4j.bolt.v3.runtime.StreamingState.processStreamResultMessage(StreamingState.java:40)
	at org.neo4j.bolt.v3.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:44)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-12-06 12:00:24.906+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]], reference 253cb64e-346d-42c4-b491-df1134fb8ca0.
2019-12-06 12:00:24.906+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]], reference 253cb64e-346d-42c4-b491-df1134fb8ca0. NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]]
java.lang.IllegalStateException: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]]
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordRelationshipTraversalCursor.computeNext(RecordRelationshipTraversalCursor.java:262)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordRelationshipTraversalCursor.next(RecordRelationshipTraversalCursor.java:157)
	at org.neo4j.kernel.impl.newapi.DefaultRelationshipTraversalCursor.next(DefaultRelationshipTraversalCursor.java:275)
	at org.neo4j.internal.kernel.api.helpers.RelationshipSparseSelection.fetchNext(RelationshipSparseSelection.java:134)
	at org.neo4j.internal.kernel.api.helpers.RelationshipSparseSelectionCursor.next(RelationshipSparseSelectionCursor.java:30)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anon$5.fetchNext(TransactionBoundQueryContext.scala:211)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anon$5.fetchNext(TransactionBoundQueryContext.scala:207)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$CursorIterator.next(TransactionBoundQueryContext.scala:1100)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:445)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.runtime.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:53)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:76)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.accept(StandardInternalExecutionResult.scala:192)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$safelyAndClose$1.apply(ClosingExecutionResult.scala:171)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.safelyAndClose(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:157)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:73)
	at org.neo4j.bolt.v1.messaging.ResultHandler.onRecords(ResultHandler.java:40)
	at org.neo4j.bolt.v3.runtime.StreamingState.lambda$processStreamResultMessage$0(StreamingState.java:41)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:484)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:328)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:128)
	at org.neo4j.bolt.v3.runtime.StreamingState.processStreamResultMessage(StreamingState.java:40)
	at org.neo4j.bolt.v3.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:44)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-12-06 12:04:34.737+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=619, gcTime=698, gcCount=1}
2019-12-06 12:04:35.542+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=402, gcTime=463, gcCount=1}
2019-12-06 12:04:39.928+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4105, gcTime=0, gcCount=0}
2019-12-06 12:04:47.469+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=858, gcTime=5273, gcCount=3}
2019-12-06 12:04:47.570+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4365, gcTime=0, gcCount=0}
2019-12-06 12:04:48.780+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=275, gcTime=285, gcCount=1}
2019-12-06 12:04:53.250+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4370, gcTime=4456, gcCount=4}
2019-12-06 12:04:58.497+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=343, gcTime=4915, gcCount=3}
2019-12-06 12:04:58.597+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4502, gcTime=0, gcCount=0}
2019-12-06 12:05:03.729+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=365, gcTime=5010, gcCount=3}
2019-12-06 12:05:03.830+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4566, gcTime=0, gcCount=0}
2019-12-06 12:05:08.991+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=109, gcTime=4707, gcCount=3}
2019-12-06 12:05:13.746+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4650, gcTime=4701, gcCount=2}
2019-12-06 12:05:13.847+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4546, gcTime=0, gcCount=0}
2019-12-06 12:05:18.797+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4549, gcTime=4624, gcCount=5}
2019-12-06 12:05:23.404+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4507, gcTime=4594, gcCount=3}
2019-12-06 12:05:27.785+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4280, gcTime=4369, gcCount=3}
2019-12-06 12:05:32.431+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4546, gcTime=4636, gcCount=3}
2019-12-06 12:05:36.788+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4256, gcTime=4347, gcCount=3}
2019-12-06 12:05:45.107+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4062, gcTime=8133, gcCount=6}
2019-12-06 12:31:03.475+0000 WARN [io.netty.channel.epoll.EpollEventLoop] Unexpected exception in the selector loop. Java heap space
java.lang.OutOfMemoryError: Java heap space
2019-12-06 12:31:03.475+0000 WARN [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.OutOfMemoryError: Java heap space' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
2019-12-06 12:31:03.475+0000 WARN [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.OutOfMemoryError: Java heap space' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
2019-12-06 12:31:17.246+0000 ERROR [o.n.b.t.TransportSelectionHandler] Fatal error occurred when initialising pipeline: [id: 0x01ae08dc, L:/192.168.208.4:7687 - R:/192.168.208.2:57982] Java heap space
java.lang.OutOfMemoryError: Java heap space
2019-12-06 12:31:17.247+0000 ERROR [o.n.b.t.TransportSelectionHandler] Fatal error occurred when initialising pipeline: [id: 0x01ae08dc, L:/192.168.208.4:7687 ! R:/192.168.208.2:57982] Java heap space
java.lang.OutOfMemoryError: Java heap space
2019-12-06 12:31:17.247+0000 ERROR [o.n.b.t.TransportSelectionHandler] Fatal error occurred when initialising pipeline: [id: 0x01ae08dc, L:/192.168.208.4:7687 ! R:/192.168.208.2:57982] refCnt: 0, decrement: 1
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.toLiveRealCnt(AbstractReferenceCountedByteBuf.java:181)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:133)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:124)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:380)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:826)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
2019-12-06 12:31:17.247+0000 WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. org.neo4j.bolt.transport.TransportSelectionHandler.handlerRemoved() has thrown an exception.
io.netty.channel.ChannelPipelineException: org.neo4j.bolt.transport.TransportSelectionHandler.handlerRemoved() has thrown an exception.
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:676)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:922)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:888)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:880)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1416)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:865)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:834)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1450)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1434)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1420)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:866)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:247)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:670)
	... 14 more
```

**Comment by YaphetKG** [comment]
I think you might be having memory issues, it looks like you have run out of heap space, try bumping up the NEO4J_HEAP  and NEO4J_INTIAL_HEAP and try loading it. The graph you are trying to load is big so that might be the issue

**Comment by Prakash2403** [comment]
Okay, will try that
