### ISSUE TITLE
Multiple Slots error in Concept

### ISSUE THREAD

**Issue by stevencox** [NCATS-Gamma/robokop#58]
I deleted my redis cache ... but get this. Is there something else I need to do?
```
127.0.0.1 - - [21/Apr/2018 13:06:53] "GET /cop/imatinib/asthma/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/scox/dev/testEnv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/scox/dev/robokop-interfaces/greent/api/server.py", line 131, in cop
    rosetta = get_rosetta ()
  File "/Users/scox/dev/robokop-interfaces/greent/api/server.py", line 99, in get_rosetta
    rosetta = Rosetta (debug=True, greentConf=config)
  File "/Users/scox/dev/robokop-interfaces/greent/rosetta.py", line 72, in __init__
    self.type_graph = TypeGraph(self.service_context, debug=debug)
  File "/Users/scox/dev/robokop-interfaces/greent/graph.py", line 42, in __init__
    self.set_concept_model()
  File "/Users/scox/dev/robokop-interfaces/greent/graph.py", line 67, in set_concept_model
    self.concept_model = ConceptModel(self.concept_model_name)
  File "/Users/scox/dev/robokop-interfaces/greent/concept.py", line 62, in __init__
    self.model_loaders[self.name] ()
  File "/Users/scox/dev/robokop-interfaces/greent/concept.py", line 59, in <lambda>
    'biolink-model' : lambda : BiolinkConceptModelLoader (name, self)
  File "/Users/scox/dev/robokop-interfaces/greent/concept.py", line 160, in __init__
    super(BiolinkConceptModelLoader, self).__init__(name, concept_model)
  File "/Users/scox/dev/robokop-interfaces/greent/concept.py", line 149, in __init__
    self.model.add_relationship(relationship)
  File "/Users/scox/dev/robokop-interfaces/greent/concept.py", line 88, in add_relationship
    raise Exception('Have multiple slots with the same mapping {}'.format(mapping))
Exception: Have multiple slots with the same mapping RO:0002302
```

**Comment by stevencox** [comment]
Commenting out the exception to make stuff run for the moment...

**Comment by cbizon** [comment]
Did you pull since yesterday?  I doubly defined an association yesterday leading to this, but fixed it late in the afternoon.  It looks ok to me now so let me know if you still see this after updating.

**Comment by kennethmorton** [comment]
Comments imply this is solved. Closing.
