### ISSUE TITLE
Missing letter in method name in caster.

### ISSUE THREAD

**Issue by stevencox** [NCATS-Gamma/robokop#59]
String slicing issue?
```

create_function: uberongraph~get_anatomy_by_cell_grap
Traceback (most recent call last):
  File "/projects/stars/app/robokop-interfaces/greent/program.py", line 97, in run_program
    op = self.rosetta.get_ops(op_name)
  File "/projects/stars/app/robokop-interfaces/greent/rosetta.py", line 147, in get_ops
    return operator.attrgetter(names)(self.core) if isinstance(names, str) else [
  File "/projects/stars/app/robokop-interfaces/greent/services/caster.py", line 77, in __getattr__
    return self.create_function(attr)
  File "/projects/stars/app/robokop-interfaces/greent/services/caster.py", line 57, in create_function
    newargs = [ self.create_function(args[0]), args[1], self.create_function(args[2])]
  File "/projects/stars/app/robokop-interfaces/greent/services/caster.py", line 63, in create_function
    newargs = [ self.create_function(args[0]), args[1] ]
  File "/projects/stars/app/robokop-interfaces/greent/services/caster.py", line 73, in create_function
    return operator.attrgetter(fname)(self.core)
AttributeError: 'UberonGraphKS' object has no attribute 'get_anatomy_by_cell_grap'

```

**Comment by cbizon** [comment]
This was a mistake in the way nested caster calls get unrolled.  But it should be ok now.  In tracking this down, I also fixed a bug in the way biolink-model overlay was working.
