### ISSUE TITLE
Exception in colocalizes_with

### ISSUE THREAD

**Issue by stevencox** [NCATS-Gamma/robokop#61]
Apparently this can happen:
```
run_program: exec op: biolink.gene_get_process(ENSEMBL:ENSG00000171132)
Traceback (most recent call last):
  File "/projects/stars/app/robokop-interfaces/greent/program.py", line 98, in run_program
    results = op(source_node)
  File "/projects/stars/app/robokop-interfaces/greent/services/biolink.py", line 98, in gene_get_process
    edges_nodes = self.process_associations(response, 'gene_get_process', node_types.PROCESS, input_id, url)
  File "/projects/stars/app/robokop-interfaces/greent/services/biolink.py", line 52, in process_associations
    standard_id, standard_label = self.standardize_predicate(predicate_id, predicate_label)
  File "/projects/stars/app/robokop-interfaces/greent/services/biolink.py", line 58, in standardize_predicate
    return self.concept_model.standardize_relationship(predicate_id)
  File "/projects/stars/app/robokop-interfaces/greent/concept.py", line 123, in standardize_relationship
    raise Exception(f"No such relationship mapped: {xref}")
Exception: No such relationship mapped: colocalizes_with
```

**Comment by cbizon** [comment]
Now if anything comes back from any biolink function that is not a curie we should be returning a single key that can be mapped to a biolink-model association.
