### ISSUE TITLE
OmniCorp get_omni_identifier

### ISSUE THREAD

**Issue by stevencox** [NCATS-Gamma/robokop#64]
Unexpected curie?
```
get_omni_identifier: {'ICD9CM:278.02', 'MESH:D050177', 'OMIM:MTHU038212', 'MeSH:D050177', 'SNOMEDCT:238131007', 'MedDRA:10033307', 'UMLS:C0497406', 'ICD10CM:E66.3', 'NCIt:C94250'}
[2018-04-26 15:15:17,024] ERROR in app: Exception on /cop/GLYBURIDE/Diabetes Mellitus, Type 2/ [GET]
Traceback (most recent call last):
  File "/projects/stars/translator/app/rosettaVenv/lib64/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/stars/translator/app/rosettaVenv/lib64/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/stars/translator/app/rosettaVenv/lib64/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/stars/translator/app/rosettaVenv/lib64/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/projects/stars/translator/app/rosettaVenv/lib64/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/stars/translator/app/rosettaVenv/lib64/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/stars/app/robokop-interfaces/greent/api/rosettad.py", line 211, in cop
    graph = gamma.knowledge.query (query, key, gamma.rosetta)
  File "/projects/stars/app/robokop-interfaces/builder/knowledgeQuery.py", line 49, in query
    kgraph.support(support_module_names=['builder.omnicorp'])
  File "/projects/stars/app/robokop-interfaces/builder/builder.py", line 347, in support
    support_edge = supporter.term_to_term(source, target)
  File "/projects/stars/app/robokop-interfaces/builder/omnicorp.py", line 22, in term_to_term
    articles = self.omnicorp.get_shared_pmids(node_a, node_b)
  File "/projects/stars/app/robokop-interfaces/greent/services/omnicorp.py", line 68, in get_shared_pmids
    id1 = self.get_omni_identifier(node1)
  File "/projects/stars/app/robokop-interfaces/greent/services/omnicorp.py", line 43, in get_omni_identifier
    oident = f'{self.prefix_to_uri[prefix]}{Text.un_curie(node.identifier)}'
KeyError: 'NCIT'
```

**Comment by cbizon** [comment]
If the curie is not part of omnicorp, it now prints a warning and returns.
